#!/usr/bin/env python3
"""ShitCam build script. NASM (win64) + MSVC link.exe, kernel32 only, no CRT."""
import os, shutil, subprocess, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VS_PATTERNS = [
    r"C:\Program Files\Microsoft Visual Studio\18\Community\VC\Tools\MSVC",
    r"C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC",
]
SDK_LIB = r"C:\Program Files (x86)\Windows Kits\10\Lib\10.0.26100.0\um\x64"

def find_nasm():
    w = shutil.which("nasm")
    if w:
        return w
    nasm_dir = os.path.join(ROOT, "tools", "nasm")
    if os.path.isdir(nasm_dir):
        for root_dir, _, files in os.walk(nasm_dir):
            if "nasm.exe" in files:
                return os.path.join(root_dir, "nasm.exe")
    print("NASM not found. Downloading portable NASM...")
    import urllib.request, zipfile
    os.makedirs(nasm_dir, exist_ok=True)
    zip_path = os.path.join(nasm_dir, "nasm.zip")
    url = "https://www.nasm.us/pub/nasm/releasebuilds/2.16.03/win64/nasm-2.16.03-win64.zip"
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
        with urllib.request.urlopen(req, timeout=30) as resp, open(zip_path, "wb") as out:
            shutil.copyfileobj(resp, out)
        with zipfile.ZipFile(zip_path, "r") as z:
            z.extractall(nasm_dir)
        try:
            os.remove(zip_path)
        except OSError:
            pass
        for root_dir, _, files in os.walk(nasm_dir):
            if "nasm.exe" in files:
                return os.path.join(root_dir, "nasm.exe")
    except Exception as e:
        print(f"Warning: Could not auto-download NASM: {e}")
    return None

def find_link():
    env = os.environ.get("LINK_EXE")
    if env and os.path.isfile(env):
        return env
    for base in VS_PATTERNS:
        if not os.path.isdir(base):
            continue
        vers = sorted(os.listdir(base), reverse=True)
        for v in vers:
            p = os.path.join(base, v, "bin", "Hostx64", "x64", "link.exe")
            if os.path.isfile(p):
                return p
    w = shutil.which("link.exe")
    return w

def run(cmd, **kw):
    print("+ " + " ".join(f'"{c}"' if " " in c else c for c in cmd))
    r = subprocess.run(cmd, **kw)
    if r.returncode != 0:
        sys.exit(f"BUILD FAILED (exit {r.returncode}): {cmd[0]}")

def write_cfg(nasm, link):
    # Baked-in toolchain paths for `shitcam build` (used via build/cfg.inc).
    # Forward slashes avoid NASM escape issues; Windows accepts them.
    def fwd(p):
        return p.replace("\\", "/")
    cfg = os.path.join(ROOT, "build", "cfg.inc")
    with open(cfg, "w", encoding="ascii") as f:
        f.write("; AUTO-GENERATED by tools/build.py - do not edit\n")
        f.write("section .data\n")
        f.write(f'cfg_nasm_exe db "{fwd(nasm)}", 0\n')
        f.write(f'cfg_link_exe db "{fwd(link)}", 0\n')
        f.write(f'cfg_sdk_lib db "{fwd(SDK_LIB)}", 0\n')
    print(f"OK: {cfg}")

def main():
    nasm = find_nasm()
    link = find_link()
    if not nasm:
        sys.exit("ERROR: NASM not found. Run tools\\nasm\\nasm-3.02\\nasm.exe expected. See README.")
    if not link:
        sys.exit("ERROR: link.exe not found. Install VS Build Tools or set LINK_EXE env.")
    if not os.path.isdir(SDK_LIB):
        sys.exit(f"ERROR: Windows SDK lib not found: {SDK_LIB}")
    build = os.path.join(ROOT, "build")
    os.makedirs(build, exist_ok=True)
    write_cfg(nasm, link)
    src = os.path.join(ROOT, "src", "shitcam.asm")
    obj = os.path.join(build, "shitcam.obj")
    exe = os.path.join(build, "shitcam.exe")
    run([nasm, "-f", "win64", "-I", ROOT + os.sep, src, "-o", obj])
    run([link, "/NOLOGO", "/SUBSYSTEM:CONSOLE", "/ENTRY:main",
         "/LARGEADDRESSAWARE:NO", "/DYNAMICBASE:NO",
         f"/OUT:{exe}", obj, "kernel32.lib", f"/LIBPATH:{SDK_LIB}"])
    print(f"OK: {exe}")

if __name__ == "__main__":
    main()
